#!/bin/bash

#SBATCH --job-name=tensorbench          # Job name for this simulation, to display on the queue
#SBATCH --time=0-06:00:00               # Maximum duration of this job. Slurm kills the job after this time
#SBATCH --nodes=8                       # Minimum nodes required for this job. Normally > 1 is only used for MPI jobs
#SBATCH --ntasks=8                      # Number of processes to launch.
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32              # Each MPI process uses 20 OpenMP threads
#SBATCH --mem-per-cpu=2000M             # Amount of RAM memory (in megabytes) required for each process
#SBATCH --output=logs/log.o      # Relative path to log file for normal console output
#SBATCH --error=logs/log.e       # Relative path to log file specifically for error output


export FLEXIBLAS=IMKL
export FLEXIBLAS_VERBOSE=1
export OMP_DISPLAY_AFFINITY=FALSE
export OMP_DISPLAY_ENV=FALSE
export OMP_MAX_ACTIVE_LEVELS=1
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
#export OMP_PLACES=cores
#export OMP_PROC_BIND=spread
export OMPI_MCA_hwloc_base_binding_policy=none

exec=../build/Release/tensorbench
fname="tbdb-tetralith.h5"
mpsbonds=[32,64,128,192,256,320,384,448,512,576,640,704,768,832,896,960,1024]
SRUNBIND="--cpu-bind=cores --distribution=block:block --hint=nomultithread --mem-bind=local"

for N in {1..8}; do
  echo "srun -N "$N" -n "$N"  $SRUNBIND $exec --facc=READWRITE  -i 10 --mpsbonds=$mpsbonds -D 2 -M 14 --fname=$fname --modes=[cyclops] --nomps=[${SLURM_CPUS_PER_TASK}]"
  srun -N "$N" -n "$N"  $SRUNBIND $exec --facc=READWRITE  -i 10 --mpsbonds=$mpsbonds -D 2 -M 14 --fname=$fname --modes=[cyclops] --nomps=[${SLURM_CPUS_PER_TASK}]
done


