if(TB_PRINT_INFO)
    # Print CMake options
    message(STATUS  "|----------------\n"
            "-- | CMAKE_BUILD_TYPE       : ${CMAKE_BUILD_TYPE}\n"
            "-- | CMAKE_PREFIX_PATH      : ${CMAKE_PREFIX_PATH}\n"
            "-- | CMAKE_INSTALL_PREFIX   : ${CMAKE_INSTALL_PREFIX}\n"
            "-- | CMAKE_VERBOSE_MAKEFILE : ${CMAKE_VERBOSE_MAKEFILE}\n"
            "-- | BUILD_SHARED_LIBS      : ${BUILD_SHARED_LIBS}\n"
            "-- | TB_DEPS_BUILD_DIR      : ${TB_DEPS_BUILD_DIR}\n"
            "-- | TB_DEPS_INSTALL_DIR    : ${TB_DEPS_INSTALL_DIR}\n"
            "-- | TB_ENABLE_EIGEN1       : ${TB_ENABLE_EIGEN1}\n"
            "-- | TB_ENABLE_EIGEN2       : ${TB_ENABLE_EIGEN2}\n"
            "-- | TB_ENABLE_EIGEN3       : ${TB_ENABLE_EIGEN3}\n"
            "-- | TB_ENABLE_CUDA         : ${TB_ENABLE_CUDA}\n"
            "-- | TB_ENABLE_ACRO         : ${TB_ENABLE_ACRO}\n"
            "-- | TB_ENABLE_CUTE         : ${TB_ENABLE_CUTE}\n"
            "-- | TB_ENABLE_MKL          : ${TB_ENABLE_MKL}\n"
            "-- | TB_ENABLE_TESTS        : ${TB_ENABLE_TESTS}\n"
            "-- | TB_ENABLE_ASAN         : ${TB_ENABLE_ASAN}\n"
            "-- | TB_ENABLE_USAN         : ${TB_ENABLE_USAN}\n"
            "-- | TB_ENABLE_LTO          : ${TB_ENABLE_LTO}\n"
            "-- | TB_ENABLE_PCH          : ${TB_ENABLE_PCH}\n"
            "-- | TB_ENABLE_CCACHE       : ${TB_ENABLE_CCACHE}\n"
            "-- | TB_ENABLE_XTENSOR      : ${TB_ENABLE_XTENSOR}\n"
            "-- | TB_ENABLE_TBLIS        : ${TB_ENABLE_TBLIS}\n"
            "-- | TB_EIGEN3_BLAS         : ${TB_EIGEN3_BLAS}\n"
            "-- | TB_BUILD_EXAMPLES      : ${TB_BUILD_EXAMPLES}\n"
            "-- | TB_PACKAGE_MANAGER     : ${TB_PACKAGE_MANAGER}\n"
            "-- | TB_PRINT_INFO          : ${TB_PRINT_INFO}\n"
            "-- | TB_PRINT_CHECKS        : ${TB_PRINT_CHECKS}\n"
            "-- | TB_DEPS_IN_SUBDIR      : ${TB_DEPS_IN_SUBDIR}"
            )
endif ()
